# Generated by Django 5.0.2 on 2024-02-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablemanagement', '0002_remove_studentdata_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='appliedCompanies',
            field=models.ManyToManyField(null=True, related_name='appliedcompanies', to='tablemanagement.companydata'),
        ),
    ]
