# Generated by Django 5.0.2 on 2024-02-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablemanagement', '0003_studentdata_appliedcompanies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydata',
            name='CTC',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
