# Generated by Django 5.0.2 on 2024-03-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablemanagement', '0005_alter_studentdata_appliedcompanies'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='resume',
            field=models.BinaryField(null=True),
        ),
    ]
