# Generated by Django 5.0.2 on 2024-03-01 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablemanagement', '0006_studentdata_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdata',
            name='resume',
        ),
    ]
