# Generated by Django 5.0.2 on 2024-03-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablemanagement', '0008_studentdata_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydata',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AddField(
            model_name='users',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
